### ISSUE TITLE
Uncaught TypeError for FullStory

### ISSUE THREAD

**Issue by gregkohn** [segmentio/action-destinations#633]
We are seeing an `Uncaught TypeError` in the console, traced back to the **FullStory action**, which is interfering with our integration testing.

The error looks a bit different between Chrome and Firefox:

**Chrome:**
```
request-client.js:57 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at request-client.js:57:32
    at a9e33b404b7263c9d6e5.js:7:45054
    at a9e33b404b7263c9d6e5.js:7:45070
    at universalModuleDefinition:9:34
    at universalModuleDefinition:1:1
```

**Firefox:**
```
Uncaught TypeError: class heritage A.CustomError is not an object or null
    <anonymous> https://cdn.segment.com/next-integrations/actions/fullstory/a9e33b404b7263c9d6e5.js:7
    <anonymous> https://cdn.segment.com/next-integrations/actions/fullstory/a9e33b404b7263c9d6e5.js:7
    <anonymous> https://cdn.segment.com/next-integrations/actions/fullstory/a9e33b404b7263c9d6e5.js:7
    <anonymous> https://cdn.segment.com/next-integrations/actions/fullstory/a9e33b404b7263c9d6e5.js:1
    <anonymous> https://cdn.segment.com/next-integrations/actions/fullstory/a9e33b404b7263c9d6e5.js:1

Source map error: Error: Invalid URL: webpack://[name]Destination/webpack/universalModuleDefinition
Resource URL: https://cdn.segment.com/next-integrations/actions/fullstory/a9e33b404b7263c9d6e5.js
Source Map URL: a9e33b404b7263c9d6e5.js.map
```

Some details on our app & Segment usage:
- Next.js app (`12.1.5`)
- Integrating with Segment via `@segment/analytics-next` (latest at time of writing, `1.38.0`)

Please let me know what other information I can provide or if I've opened this in the wrong spot!
Thanks 🙏

**Comment by pooyaj** [comment]
Hi @gregkohn, you've come to the right spot! Is it possible to share the link to your website so we can reproduce this?

**Comment by gregkohn** [comment]
Thanks for the quick response! Of course -- https://www.acrehomes.com/
It's frustratingly intermittent so it's not always easy to reproduce, but should pop up. Let me know if I there's anything else you need.
